In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)

In [2]:
a

array([1, 2, 3])

In [3]:
b=[[1,2,3],[2,3,4],[3,4,5]]
b=np.array(b)

In [4]:
b.shape

(3, 3)

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((5,5))+5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [11]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [12]:
#to get evenly spaced numbers between any 2 numbers
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# it will return 4 random numbers between 0 and 1
np.random.rand(4)

array([0.44395113, 0.09647754, 0.42959173, 0.54035232])

In [17]:
np.random.rand(5,5)

array([[0.29887257, 0.59871589, 0.69609779, 0.3757255 , 0.6754458 ],
       [0.58353487, 0.37845863, 0.33107894, 0.77200433, 0.86281569],
       [0.39805582, 0.36277713, 0.38287548, 0.04557301, 0.34477633],
       [0.71515668, 0.22686019, 0.35734243, 0.16517311, 0.8540986 ],
       [0.36096273, 0.18815522, 0.3026794 , 0.74013294, 0.62150152]])

In [18]:
# return numbers for normal distribution. this return samples from standard normal distributon :mean=0 SD=1
np.random.randn(1)

array([1.36520351])

In [19]:
np.random.randn(10)

array([ 1.2481957 ,  0.5927671 , -0.58803408,  0.48128572,  0.84176736,
        0.56015726,  0.25853319,  0.93645467, -0.4200308 ,  0.29904189])

In [22]:
# here we can change the mean and standard deviation by using np.random.normal where loc is mean and scale is standard deviation
np.random.normal(loc=0,scale=1,size=10)

array([ 0.10078226,  1.5063934 , -1.02212246,  0.5118705 , -0.60011807,
       -2.37598835,  1.19869091, -0.41559117, -0.09436873, -0.57481539])

In [29]:
#randint is used to generate random integers
np.random.randint(1,100,10)

array([25, 50, 19, 11, 78, 80, 40, 68, 72,  9])

In [32]:
# we use seed to always get the same random numbers multiple times for future reference in code
#***seed and the operations u want to perform should be in same cell.
np.random.seed(479) # 479 is a arbitary number chosen and it can be anything 
np.random.rand(4,4)

array([[2.89114106e-02, 8.18236100e-01, 9.54782571e-01, 2.57275241e-01],
       [2.97158282e-01, 2.98709495e-04, 5.58329318e-01, 4.31890352e-01],
       [3.67677752e-01, 1.80768678e-01, 5.21407183e-01, 3.55872721e-01],
       [1.60714384e-01, 6.33168976e-01, 6.29332065e-01, 2.75666432e-01]])

In [36]:
# sometimes we want to reshape the arrays
arr=np.arange(25)
arr
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranrr=np.random.randint(10,50,10)
ranrr.max()

45

In [41]:
ranrr

array([40, 26, 16, 31, 25, 25, 25, 44, 34, 45])

In [38]:
ranrr.min()

16

In [40]:
ranrr.argmax()

9

In [42]:
ranrr.argmin()

2

In [44]:
#to get the type of numpy array
ranrr.dtype

dtype('int32')

In [45]:
#slicing
a=[[1,2,3],[2,3,4],[5,6,7]]
a=np.array(a)
a[:2,1:]

array([[2, 3],
       [3, 4]])

In [48]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
#now lets do sum across the rows in a 2d matrix
arr_2d=np.arange(1,13)
arr_2d=arr_2d.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr_2d.sum()

78

In [56]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [57]:
arr_2d.sum(axis=1)

array([10, 26, 42])